# Generated by Django 3.1.1 on 2021-04-25 10:48

from django.db import migrations, models
import stdimage.models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_usuario_foto'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
                ('objects', users.models.UsuarioManager()),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='img',
            field=stdimage.models.StdImageField(blank=True, default=False, upload_to='imagem_user', verbose_name='Imagem:'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='status_email',
            field=models.BooleanField(default=False, verbose_name='Status email'),
        ),
    ]
